package com.sdkdjn.atmbms.connection;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

//装饰设计模式
public class MyConnection implements Connection {

	private Connection oldConnection;// com.mysql.jdbc.Connection
	private List<Connection> pool;// 连接池对象

	public MyConnection(Connection oldConnection, List<Connection> pool) {
		this.oldConnection = oldConnection;// 得到com.mysql.jdbc.Connection
		this.pool = pool;// 得到连接池对象
	}

	// 重写close方法
	public void close() throws SQLException {
		pool.add(oldConnection);
	}

	public PreparedStatement prepareStatement(String sql) throws SQLException {
		return oldConnection.prepareStatement(sql);
	}

	public <T> T unwrap(Class<T> iface) throws SQLException {
		return oldConnection.unwrap(iface);
	}

	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		return oldConnection.isWrapperFor(iface);
	}

	public Statement createStatement() throws SQLException {
		return oldConnection.createStatement();
	}

	public CallableStatement prepareCall(String sql) throws SQLException {
		return oldConnection.prepareCall(sql);
	}

	public void setAutoCommit(boolean autoCommit) throws SQLException {
		oldConnection.setAutoCommit(autoCommit);

	}

	public boolean getAutoCommit() throws SQLException {
		return oldConnection.getAutoCommit();
	}

	public void commit() throws SQLException {
		oldConnection.commit();

	}

	public void rollback() throws SQLException {
		oldConnection.rollback();
	}

	public String nativeSQL(String sql) throws SQLException {
		return null;
	}

	public boolean isClosed() throws SQLException {
		return false;
	}

	public DatabaseMetaData getMetaData() throws SQLException {
		return null;
	}

	public void setReadOnly(boolean readOnly) throws SQLException {

	}

	public boolean isReadOnly() throws SQLException {
		return false;
	}

	public void setCatalog(String catalog) throws SQLException {

	}

	public String getCatalog() throws SQLException {
		return null;
	}

	public void setTransactionIsolation(int level) throws SQLException {

	}

	public int getTransactionIsolation() throws SQLException {
		return 0;
	}

	public SQLWarning getWarnings() throws SQLException {
		return null;
	}

	public void clearWarnings() throws SQLException {

	}

	public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {

		return null;
	}

	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
			throws SQLException {

		return null;
	}

	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {

		return null;
	}

	public Map<String, Class<?>> getTypeMap() throws SQLException {

		return null;
	}

	public void setTypeMap(Map<String, Class<?>> map) throws SQLException {

	}

	public void setHoldability(int holdability) throws SQLException {

	}

	public int getHoldability() throws SQLException {

		return 0;
	}

	public Savepoint setSavepoint() throws SQLException {

		return null;
	}

	public Savepoint setSavepoint(String name) throws SQLException {

		return null;
	}

	public void rollback(Savepoint savepoint) throws SQLException {

	}

	public void releaseSavepoint(Savepoint savepoint) throws SQLException {

	}

	public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability)
			throws SQLException {

		return null;
	}

	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency,
			int resultSetHoldability) throws SQLException {

		return null;
	}

	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency,
			int resultSetHoldability) throws SQLException {

		return null;
	}

	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {

		return null;
	}

	public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {

		return null;
	}

	public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {

		return null;
	}

	public Clob createClob() throws SQLException {

		return null;
	}

	public Blob createBlob() throws SQLException {

		return null;
	}

	public NClob createNClob() throws SQLException {

		return null;
	}

	public SQLXML createSQLXML() throws SQLException {

		return null;
	}

	public boolean isValid(int timeout) throws SQLException {

		return false;
	}

	public void setClientInfo(String name, String value) throws SQLClientInfoException {

	}

	public void setClientInfo(Properties properties) throws SQLClientInfoException {

	}

	public String getClientInfo(String name) throws SQLException {

		return null;
	}

	public Properties getClientInfo() throws SQLException {

		return null;
	}

	public Array createArrayOf(String typeName, Object[] elements) throws SQLException {

		return null;
	}

	public Struct createStruct(String typeName, Object[] attributes) throws SQLException {

		return null;
	}

	@Override
	public void setSchema(String schema) throws SQLException {

	}

	@Override
	public String getSchema() throws SQLException {

		return null;
	}

	@Override
	public void abort(Executor executor) throws SQLException {

	}

	@Override
	public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {

	}

	@Override
	public int getNetworkTimeout() throws SQLException {

		return 0;
	}

}
